export const voices = [
  { id: 'algenib', name: 'Algenib (Female)' },
  { id: 'achernar', name: 'Achernar (Male)' },
  { id: 'gacrux', name: 'Gacrux (Female)' },
  { id: 'iapetus', name: 'Iapetus (Male)' },
  { id: 'kore', name: 'Kore (Female)' },
  { id: 'leda', name: 'Leda (Male)' },
  { id: 'puck', name: 'Puck (Female)' },
  { id: 'sadachbia', name: 'Sadachbia (Male)' },
  { id: 'schedar', name: 'Schedar (Female)' },
  { id: 'zephyr', name: 'Zephyr (Male)' },
  { id: 'achird', name: 'Achird (Female)' },
  { id: 'algieba', name: 'Algeiba (Male)' },
  { id: 'alnilam', name: 'Alnilam (Male)' },
  { id: 'aoede', name: 'Aoede (Female)' },
  { id: 'charon', name: 'Charon (Male)' },
  { id: 'despina', name: 'Despina (Female)' },
  { id: 'enceladus', name: 'Enceladus (Male)' },
  { id: 'erinome', name: 'Erinome (Female)' },
  { id: 'fenrir', name: 'Fenrir (Male)' },
  { id: 'laomedeia', name: 'Laomedeia (Female)' },
  { id: 'orus', name: 'Orus (Male)' },
  { id: 'rasalgethi', name: 'Rasalgethi (Male)' },
  { id: 'sulafat', name: 'Sulafat (Female)' },
  { id: 'umbriel', name: 'Umbriel (Male)' },
  { id: 'vindemiatrix', name: 'Vindemiatrix (Female)' },
  { id: 'zubenelgenubi', name: 'Zubenelgenubi (Male)' },
];
